### ISSUE TITLE
Please reply

### ISSUE THREAD

**Issue by dinosy817** [danzisky/test-q-and-a-backend#1]
Hello
I am a Full stack and Blockchain developer
If you have several ongoing project, I want to cooperate with you.

This is my contact info.
skype: live:.cid.21d53029f8ceb0c7
discord: apollo_268425

I hope to hear good news from you soon.
Thanks.

**Comment by danzisky** [comment]
Hello,

Thank you for reaching out.

Currently, I am working on more private projects which are not mine. But if I resume working on those I have more control over and which you'll be a great fit for, I'll try reaching out.

Thank you, do have a great day!

**Comment by dinosy817** [comment]
Thank you for your reply.
And I want to communicate with you on skype or discord.
If you don't mind, please contact me.
Thanks.
